Repository KMKfw/kmk_firmware, pull requests merged in 2020-10, with the labels that each got.

#170 Allows continuation of firmware if bluetooth can't be imported
  kmk/kmk_keyboard.py
Labels: bluetooth/wireless, bug

#167 BLE Multiple Connections
  docs/keycodes.md
  kmk/ble.py
  kmk/handlers/stock.py
  kmk/keys.py
  user_keymaps/dzervas/lab68.py
Labels: bluetooth/wireless, enhancement

#180 update RGB for more modern cpy versions
  kmk/kmk_keyboard.py
  kmk/rgb.py
Labels: general firmware
