Repository KMKfw/kmk_firmware, pull requests merged in 2021-09, with the labels that each got.

#231 add / to key names
  kmk/keys.py
Labels: bug, general firmware

#243 always release the same key as was pressed
  kmk/handlers/stock.py
  kmk/kmk_keyboard.py
Labels: bug, general firmware

#232 Convert to supervisor ticks
  kmk/handlers/stock.py
  kmk/kmk_keyboard.py
  kmk/kmktime.py
  kmk/modules/encoder.py
  kmk/modules/layers.py
  kmk/modules/modtap.py
  kmk/modules/power.py
  kmk/modules/split.py
Labels: enhancement

#246 Improve hold tap (MT, LT, TT) behaviour
  kmk/kmk_keyboard.py
  kmk/modules/holdtap.py
  kmk/modules/layers.py
  kmk/modules/modtap.py
Labels: enhancement, general firmware

#247 fix tapdancing
  kmk/kmk_keyboard.py
Labels: bug

#249 Fix LT() doesn't work
  kmk/modules/layers.py
Labels: bug
