Repository KMKfw/kmk_firmware, pull requests merged in 2022-10, with the labels that each got.

#610 added Raspberry Pi Pico pinouts for the Pimoroni Keybow: Maintainer edit
  boards/pimoroni/keybow/keybow.py
Labels: community boards

#609 Boot.py docs better example
  docs/boot.md
Labels: Documentation

#602 add type hinting for kmk.keys
  kmk/keys.py
Labels: type hinting
