Repository KMKfw/kmk_firmware, pull requests merged in 2022-09, with the labels that each got.

#569 More Lulu cleanup
  boards/boardsource/Lulu/README.md
Labels: Documentation

#595 Set sandbox.matrix_update
  kmk/kmk_keyboard.py
Labels: bug

#592 Add key coord combos - Replaces #587
  docs/combos.md
  kmk/modules/combos.py
Labels: extension

#596 sequences update with new example
  docs/sequences.md
Labels: Documentation
